name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        type: string
        required: true
        description: "The tag of the generated docker image"
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bishoybasily/graalvm-ce:${{ github.event.inputs.docker_image_tag }}, bishoybasily/graalvm-ce:latest

